language: node_js

node_js:
  - stable

addons:
  firefox: latest
  chrome: stable

services:
  - xvfb

before_script:
  - export DISPLAY=:99.0

script:
  - npm test
  - npm run test:browserstack
  # Remove BrowserStackLocal binary to avoid ETXTBSY error
  - rm -f node_modules/browserstack-runner/lib/BrowserStackLocal
  - npm run test:browserstack-legacy
