language: node_js

node_js:
  - stable

addons:
  firefox: latest
  chrome: stable

services:
  - xvfb

cache:
  directories:
    - $HOME/.compat-data

before_script:
  - export DISPLAY=:99.0

script:
  - npm test
  - npm run test:browserstack
  - npm run test:browserstack-legacy
